autoInstallPeers: false
publicHoistPattern:
  - '*storybook*'
# Enforce that packages must be at least 2 days old before they're installed
# This reduces the risk of supply chain attacks from newly published packages
minimumReleaseAge: 2880
packages:
  - 'packages/**'
  - '!**/dist/**'
  - '!**/.next/**'
  - '!packages/myso/test/**'
  - '!packages/codegen/tests/move/**'
  - '!packages/create-dapp/templates/*/move/**'
  - '!packages/myso/scripts'
  - '!packages/myso/transactions'
  - '!packages/myso/cryptography'
  - '!packages/myso/faucet'
  - '!packages/myso/client'
  - '!packages/myso/verify'
  - '!packages/myso/multisig'
  - '!packages/myso/utils'
  - '!packages/myso/bcs'
  - '!packages/enoki/react'
  - '!packages/myso/graphql'
  - '!packages/myso/keypairs/ed25519'
  - '!packages/myso/keypairs/secp256k1'
  - '!packages/myso/keypairs/secp256r1'
  - '!packages/myso/graphql/schemas/2024.1'
  - '!packages/myso/graphql/schemas/2024.4'
  - '!packages/signers/aws'
  - '!packages/signers/gcp'
  - '!packages/signers/ledger'
  - '!packages/myso/zklogin'
  - '!packages/myso/keypairs/passkey'
  - '!packages/myso/graphql/schema'
  - '!packages/signers/utils'
  - '!packages/signers/webcrypto'
  - '!packages/zksend/experimental/unified-adapter'
  - '!packages/myso/experimental'
  - '!packages/dapp-kit-next/packages/dapp-kit-core/web'
  - '!packages/myso/grpc'
  - '!packages/myso/jsonRpc'
