// Copyright (c) Mysten Labs, Inc.
// Copyright (c) The Social Proof Foundation, LLC.
// SPDX-License-Identifier: Apache-2.0

import { readFile, writeFile } from 'fs/promises';
import TOML from '@iarna/toml';

const LICENSE = '// Copyright (c) Mysten Labs, Inc.\n// SPDX-License-Identifier: Apache-2.0\n\n';

const WARNING = '// This file is generated by genversion.mjs. Do not edit it directly.\n\n';

async function main() {
	const pkg = JSON.parse(await readFile('./package.json', 'utf8'));
	const cargo = TOML.parse(
		await fetch('https://raw.githubusercontent.com/The-Social-Proof-Foundation/myso-core/main/Cargo.toml').then(
			async (res) => {
				if (!res.ok) throw new Error(`Failed to fetch Cargo.toml: ${res.status} ${res.statusText}`);
				return res.text();
			},
		),
	);
	await writeFile(
		'src/version.ts',
		LICENSE +
			WARNING +
			`export const PACKAGE_VERSION = '${pkg.version}';\nexport const TARGETED_RPC_VERSION = '${cargo.workspace.package.version}';\n`,
	);
}

await main();
